[2023-06-05T17:47:43.928+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather.add_data_in_weather scheduled__2023-05-22T02:01:00+00:00 [queued]>
[2023-06-05T17:47:43.997+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather.add_data_in_weather scheduled__2023-05-22T02:01:00+00:00 [queued]>
[2023-06-05T17:47:43.997+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-05T17:47:43.997+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-06-05T17:47:43.997+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-05T17:47:44.467+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): add_data_in_weather> on 2023-05-22 02:01:00+00:00
[2023-06-05T17:47:44.502+0000] {standard_task_runner.py:55} INFO - Started process 11819 to run task
[2023-06-05T17:47:44.514+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather', 'add_data_in_weather', 'scheduled__2023-05-22T02:01:00+00:00', '--job-id', '625', '--raw', '--subdir', 'DAGS_FOLDER/weather_DAG.py', '--cfg-path', '/tmp/tmp2g0y3j36']
[2023-06-05T17:47:44.535+0000] {standard_task_runner.py:83} INFO - Job 625: Subtask add_data_in_weather
[2023-06-05T17:47:44.750+0000] {task_command.py:388} INFO - Running <TaskInstance: weather.add_data_in_weather scheduled__2023-05-22T02:01:00+00:00 [running]> on host 05172cfd5782
[2023-06-05T17:47:44.941+0000] {abstractoperator.py:615} ERROR - Exception rendering Jinja template for task 'add_data_in_weather', field 'sql'. Template: "\n            insert into weather_data (date, current_temperature, feels_like, sky, chance_of_precipitation, wind, \n            pressure, uv_index, humidity, precipitation) values \n            ('{{ti.xcom_pull(task_ids='scraping weather')[0]}}',\n            '{{ti.xcom_pull(task_ids='scraping weather')[1]}}',\n            '{{ti.xcom_pull(task_ids='scraping weather')[2]}}',\n            '{{ti.xcom_pull(task_ids='scraping weather')[3]}}',\n            '{{ti.xcom_pull(task_ids='scraping weather')[4]}}',\n            '{{ti.xcom_pull(task_ids='scraping weather')[5]}}',\n            '{{ti.xcom_pull(task_ids='scraping weather')[6]}}',\n            '{{ti.xcom_pull(task_ids='scraping weather')[7]}}',\n            '{{ti.xcom_pull(task_ids='scraping weather')[8]}}',\n            '{{ti.xcom_pull(task_ids='scraping weather')[9]}}'\n            )\n            "
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 665, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-06-05T17:47:44.943+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 665, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-06-05T17:47:44.957+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=weather, task_id=add_data_in_weather, execution_date=20230522T020100, start_date=20230605T174743, end_date=20230605T174744
[2023-06-05T17:47:44.976+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 625 for task add_data_in_weather (None has no element 0; 11819)
[2023-06-05T17:47:44.998+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-05T17:47:45.140+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
