[2023-05-25T17:02:30.726+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.add_data manual__2023-05-24T17:09:20.161548+00:00 [queued]>
[2023-05-25T17:02:30.750+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.add_data manual__2023-05-24T17:09:20.161548+00:00 [queued]>
[2023-05-25T17:02:30.751+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-25T17:02:30.751+0000] {taskinstance.py:1283} INFO - Starting attempt 28 of 32
[2023-05-25T17:02:30.751+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-25T17:02:30.785+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): add_data> on 2023-05-24 17:09:20.161548+00:00
[2023-05-25T17:02:30.792+0000] {standard_task_runner.py:55} INFO - Started process 3010 to run task
[2023-05-25T17:02:30.796+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'add_data', 'manual__2023-05-24T17:09:20.161548+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmp550hyjx8']
[2023-05-25T17:02:30.798+0000] {standard_task_runner.py:83} INFO - Job 224: Subtask add_data
[2023-05-25T17:02:31.029+0000] {task_command.py:388} INFO - Running <TaskInstance: ETL.add_data manual__2023-05-24T17:09:20.161548+00:00 [running]> on host 2fa3ade57007
[2023-05-25T17:02:31.087+0000] {abstractoperator.py:615} ERROR - Exception rendering Jinja template for task 'add_data', field 'sql'. Template: "\n            insert into spotify_data (played_at) values ('{{spotify_df['played_at']}}')\n        "
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 665, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 303, in getitem
    return obj[argument]
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'spotify_df' is undefined
[2023-05-25T17:02:31.089+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 665, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 303, in getitem
    return obj[argument]
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'spotify_df' is undefined
[2023-05-25T17:02:31.107+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL, task_id=add_data, execution_date=20230524T170920, start_date=20230525T170230, end_date=20230525T170231
[2023-05-25T17:02:31.126+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 224 for task add_data ('spotify_df' is undefined; 3010)
[2023-05-25T17:02:31.172+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-25T17:02:31.200+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
