[2023-05-23T17:33:05.917+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.token manual__2023-05-23T17:10:43.672559+00:00 [queued]>
[2023-05-23T17:33:05.965+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.token manual__2023-05-23T17:10:43.672559+00:00 [queued]>
[2023-05-23T17:33:05.965+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T17:33:05.966+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-05-23T17:33:05.966+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T17:33:06.042+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): token> on 2023-05-23 17:10:43.672559+00:00
[2023-05-23T17:33:06.052+0000] {standard_task_runner.py:55} INFO - Started process 2834 to run task
[2023-05-23T17:33:06.064+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'token', 'manual__2023-05-23T17:10:43.672559+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmpmd3y1y_w']
[2023-05-23T17:33:06.065+0000] {standard_task_runner.py:83} INFO - Job 49: Subtask token
[2023-05-23T17:33:06.233+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.token manual__2023-05-23T17:10:43.672559+00:00 [running]> on host 2a789c3fa429
[2023-05-23T17:33:06.415+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=token
AIRFLOW_CTX_EXECUTION_DATE=2023-05-23T17:10:43.672559+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-23T17:10:43.672559+00:00
[2023-05-23T17:33:06.416+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/refresh_token_DAG.py", line 41, in token
    token = ti.xcoms_pull(task_ids='a.refresh')
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'
[2023-05-23T17:33:06.434+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_token, task_id=token, execution_date=20230523T171043, start_date=20230523T173305, end_date=20230523T173306
[2023-05-23T17:33:06.468+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 49 for task token ('TaskInstance' object has no attribute 'xcoms_pull'; 2834)
[2023-05-23T17:33:06.528+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-23T17:33:06.585+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
