[2023-05-24T16:13:37.153+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.ETL manual__2023-05-23T17:54:32.171118+00:00 [queued]>
[2023-05-24T16:13:37.173+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.ETL manual__2023-05-23T17:54:32.171118+00:00 [queued]>
[2023-05-24T16:13:37.173+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T16:13:37.173+0000] {taskinstance.py:1283} INFO - Starting attempt 13 of 18
[2023-05-24T16:13:37.174+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T16:13:37.206+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): ETL> on 2023-05-23 17:54:32.171118+00:00
[2023-05-24T16:13:37.218+0000] {standard_task_runner.py:55} INFO - Started process 1896 to run task
[2023-05-24T16:13:37.218+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'ETL', 'manual__2023-05-23T17:54:32.171118+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmprhj0nggp']
[2023-05-24T16:13:37.225+0000] {standard_task_runner.py:83} INFO - Job 115: Subtask ETL
[2023-05-24T16:13:37.333+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.ETL manual__2023-05-23T17:54:32.171118+00:00 [running]> on host 2fa3ade57007
[2023-05-24T16:13:37.494+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=ETL
AIRFLOW_CTX_EXECUTION_DATE=2023-05-23T17:54:32.171118+00:00
AIRFLOW_CTX_TRY_NUMBER=13
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-23T17:54:32.171118+00:00
[2023-05-24T16:13:37.497+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: run_spotify_etl() missing 1 required positional argument: 'token'
[2023-05-24T16:13:37.515+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_token, task_id=ETL, execution_date=20230523T175432, start_date=20230524T161337, end_date=20230524T161337
[2023-05-24T16:13:37.537+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 115 for task ETL (run_spotify_etl() missing 1 required positional argument: 'token'; 1896)
[2023-05-24T16:13:37.557+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-24T16:13:37.587+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
