[2023-05-22T16:30:05.316+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.fresh scheduled__2023-05-21T00:00:00+00:00 [queued]>
[2023-05-22T16:30:05.330+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.fresh scheduled__2023-05-21T00:00:00+00:00 [queued]>
[2023-05-22T16:30:05.330+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-22T16:30:05.331+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 6
[2023-05-22T16:30:05.331+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-22T16:30:05.359+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): fresh> on 2023-05-21 00:00:00+00:00
[2023-05-22T16:30:05.367+0000] {standard_task_runner.py:55} INFO - Started process 1293 to run task
[2023-05-22T16:30:05.372+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'fresh', 'scheduled__2023-05-21T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmpj9l04v3v']
[2023-05-22T16:30:05.372+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask fresh
[2023-05-22T16:30:05.464+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.fresh scheduled__2023-05-21T00:00:00+00:00 [running]> on host 3dac4c67abd7
[2023-05-22T16:30:05.582+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=fresh
AIRFLOW_CTX_EXECUTION_DATE=2023-05-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-21T00:00:00+00:00
[2023-05-22T16:30:05.584+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: refresh() missing 1 required positional argument: 'self'
[2023-05-22T16:30:05.603+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_token, task_id=fresh, execution_date=20230521T000000, start_date=20230522T163005, end_date=20230522T163005
[2023-05-22T16:30:05.628+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task fresh (refresh() missing 1 required positional argument: 'self'; 1293)
[2023-05-22T16:30:05.679+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-22T16:30:05.714+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
