[2023-05-24T15:28:44.553+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.token scheduled__2023-05-23T00:00:00+00:00 [queued]>
[2023-05-24T15:28:44.569+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.token scheduled__2023-05-23T00:00:00+00:00 [queued]>
[2023-05-24T15:28:44.569+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T15:28:44.569+0000] {taskinstance.py:1283} INFO - Starting attempt 7 of 7
[2023-05-24T15:28:44.569+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T15:28:44.589+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): token> on 2023-05-23 00:00:00+00:00
[2023-05-24T15:28:44.596+0000] {standard_task_runner.py:55} INFO - Started process 633 to run task
[2023-05-24T15:28:44.602+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'token', 'scheduled__2023-05-23T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmpflry0bwk']
[2023-05-24T15:28:44.604+0000] {standard_task_runner.py:83} INFO - Job 87: Subtask token
[2023-05-24T15:28:44.683+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.token scheduled__2023-05-23T00:00:00+00:00 [running]> on host 2fa3ade57007
[2023-05-24T15:28:44.779+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=token
AIRFLOW_CTX_EXECUTION_DATE=2023-05-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-23T00:00:00+00:00
[2023-05-24T15:28:44.794+0000] {logging_mixin.py:137} INFO - None
[2023-05-24T15:28:45.171+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Spotify_ETL.py", line 60, in run_spotify_etl
    for song in resource['items']:
KeyError: 'items'
[2023-05-24T15:28:45.180+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=refresh_token, task_id=token, execution_date=20230523T000000, start_date=20230524T152844, end_date=20230524T152845
[2023-05-24T15:28:45.200+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 87 for task token ('items'; 633)
[2023-05-24T15:28:45.212+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-24T15:28:45.236+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
