[2023-05-25T15:40:34.741+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.load_date manual__2023-05-24T17:09:20.161548+00:00 [queued]>
[2023-05-25T15:40:34.764+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.load_date manual__2023-05-24T17:09:20.161548+00:00 [queued]>
[2023-05-25T15:40:34.764+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-25T15:40:34.764+0000] {taskinstance.py:1283} INFO - Starting attempt 9 of 14
[2023-05-25T15:40:34.765+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-25T15:40:34.787+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): load_date> on 2023-05-24 17:09:20.161548+00:00
[2023-05-25T15:40:34.793+0000] {standard_task_runner.py:55} INFO - Started process 783 to run task
[2023-05-25T15:40:34.796+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'load_date', 'manual__2023-05-24T17:09:20.161548+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmp0tjl57s4']
[2023-05-25T15:40:34.798+0000] {standard_task_runner.py:83} INFO - Job 191: Subtask load_date
[2023-05-25T15:40:35.009+0000] {task_command.py:388} INFO - Running <TaskInstance: ETL.load_date manual__2023-05-24T17:09:20.161548+00:00 [running]> on host 2fa3ade57007
[2023-05-25T15:40:35.099+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=ETL
AIRFLOW_CTX_TASK_ID=load_date
AIRFLOW_CTX_EXECUTION_DATE=2023-05-24T17:09:20.161548+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-24T17:09:20.161548+00:00
[2023-05-25T15:40:35.418+0000] {python.py:177} INFO - Done. Returned value was:                   played_at  ...  timestamps
0  2023-05-24T09:27:03.506Z  ...  2023-05-24
1  2023-05-24T09:13:18.726Z  ...  2023-05-24
2  2023-05-24T09:02:43.570Z  ...  2023-05-24
3  2023-05-24T08:57:23.618Z  ...  2023-05-24
4  2023-05-24T08:51:46.910Z  ...  2023-05-24
5  2023-05-24T08:45:04.757Z  ...  2023-05-24
6  2023-05-24T08:40:18.392Z  ...  2023-05-24
7  2023-05-24T08:36:58.155Z  ...  2023-05-24
8  2023-05-24T08:33:03.048Z  ...  2023-05-24
9  2023-05-24T08:29:23.431Z  ...  2023-05-24

[10 rows x 4 columns]
[2023-05-25T15:40:35.441+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-05-25T15:40:35.443+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2304, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-05-25T15:40:35.454+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL, task_id=load_date, execution_date=20230524T170920, start_date=20230525T154034, end_date=20230525T154035
[2023-05-25T15:40:35.469+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 191 for task load_date (Object of type DataFrame is not JSON serializable; 783)
[2023-05-25T15:40:35.493+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-25T15:40:35.659+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
